root = "."

# Config file for Air
[build]
    # Command to build the app
    cmd = "go mod download && go build -o ./tmp/main ./cmd/api/main.go"
    # Binary to watch
    bin = "./tmp/main"
    # Working directory
    dir = "."
    # Patterns to watch
    include_ext = ["go"]
    # Exclude files
    exclude_dir = ["vendor", "tmp"]
    # Command to run after build
    run_after_build = "chmod +x ./tmp/main"

    poll = true
    poll_interval = 1

[log]
    level = "debug"