services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - "8080:8080"
        env_file:
            - .env
        environment:
            - GIN_MODE=release
