// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package session

import (
	"github.com/google/wire"
	"github.com/philipnathan/pijar-backend/internal/learner/repository"
	"github.com/philipnathan/pijar-backend/internal/session/handler"
	session2 "github.com/philipnathan/pijar-backend/internal/session/repository"
	session3 "github.com/philipnathan/pijar-backend/internal/session/service"
	"gorm.io/gorm"
)

// Injectors from session_wire.go:

func InitializedSession(db *gorm.DB) (session.SessionHandlerInterface, error) {
	sessionRepository := session2.NewSessionRepository(db)
	learnerRepositoryInterface := learner.NewLearnerRepository(db)
	sessionService := session3.NewSessionService(sessionRepository, learnerRepositoryInterface)
	sessionHandlerInterface := session.NewSessionHandler(sessionService)
	return sessionHandlerInterface, nil
}

// session_wire.go:

var SessionProviderSet = wire.NewSet(session2.NewSessionRepository, session3.NewSessionService, session.NewSessionHandler)
