// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package category

import (
	"github.com/google/wire"
	"github.com/philipnathan/pijar-backend/internal/category/handler"
	category2 "github.com/philipnathan/pijar-backend/internal/category/repository"
	category3 "github.com/philipnathan/pijar-backend/internal/category/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializedCategory(db *gorm.DB) (*category.CategoryHandler, error) {
	categoryRepository := category2.NewCategoryRepository(db)
	categoryService := category3.NewCategoryService(categoryRepository)
	categoryHandler := category.NewCategoryHandler(categoryService)
	return categoryHandler, nil
}

// wire.go:

var ProviderSet = wire.NewSet(category2.NewCategoryRepository, category3.NewCategoryService, category.NewCategoryHandler)
