// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package notification

import (
	"github.com/google/wire"
	"github.com/philipnathan/pijar-backend/internal/notification/handler"
	notification2 "github.com/philipnathan/pijar-backend/internal/notification/repository"
	notification3 "github.com/philipnathan/pijar-backend/internal/notification/service"
	"gorm.io/gorm"
)

// Injectors from notification_wire.go:

func InitializedNotification(db *gorm.DB) (notification.NotificationHandlerInterface, error) {
	notificationRepositoryInterface := notification2.NewNotificationRepository(db)
	notificationServiceInterface := notification3.NewNotificationService(notificationRepositoryInterface)
	notificationHandlerInterface := notification.NewNotificationHandler(notificationServiceInterface)
	return notificationHandlerInterface, nil
}

// notification_wire.go:

var NotificationProviderSet = wire.NewSet(notification2.NewNotificationRepository, notification3.NewNotificationService, notification.NewNotificationHandler)
