// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"github.com/google/wire"
	"github.com/philipnathan/pijar-backend/internal/user/handler"
	user2 "github.com/philipnathan/pijar-backend/internal/user/repository"
	user3 "github.com/philipnathan/pijar-backend/internal/user/service"
	"gorm.io/gorm"
)

// Injectors from user_wire.go:

func InitializedUser(db *gorm.DB) (user.UserHandlerInterface, error) {
	userRepositoryInterface := user2.NewUserRepository(db)
	userServiceInterface := user3.NewUserService(userRepositoryInterface)
	userHandlerInterface := user.NewUserHandler(userServiceInterface)
	return userHandlerInterface, nil
}

// user_wire.go:

var UserProviderSet = wire.NewSet(user2.NewUserRepository, user3.NewUserService, user.NewUserHandler)
